# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Install OS-level dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    libgl1-mesa-glx \
    libevent-dev \
    libglib2.0-0 \
    build-essential \
    libssl-dev \
    libffi-dev 
    #rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
# Using --no-cache-dir to keep the image size down
RUN pip install --no-cache-dir --trusted-host pypi.python.org \
    Flask \
    opencv-python-headless \
    ultralytics \
    flask_wtf \
    gunicorn \
    gevent

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable for Flask to run in production mode
ENV FLASK_ENV=production

# Run app.py when the container launches
CMD ["python", "app.py"]
#CMD ["gunicorn", "-w", "4", "-t", "120", "-k", "gevent", "--bind", "0.0.0.0:5000", "app:app"]
